name: Publish to BCR
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The release tag to publish (e.g., v1.2.3)"
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@d07b5b1e1a6364b402e33146f5ae6984a9363162 # v0.2.1
    with:
      tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || github.event.release.tag_name }}
      registry_fork: cgrindel/bazel-central-registry
      attest: false
    secrets:
      BCR_PUBLISH_TOKEN: ${{ secrets.BCR_PUBLISH_TOKEN }}
